In [1]:
import torch

In [2]:
t1=torch.tensor(4.)

In [3]:
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
t2=torch.tensor([1.,2,3,4])

In [6]:
t2

tensor([1., 2., 3., 4.])

In [7]:
t2.dtype

torch.float32

In [8]:
t3=torch.tensor([[1.,2,3],[4,5,6],[7,8,9]])

In [9]:
t3

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [10]:
t3.dtype

torch.float32

In [11]:
t3.shape

torch.Size([3, 3])

In [12]:
t4=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [13]:
t4

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [14]:
t4.shape

torch.Size([2, 2, 3])

In [15]:
t1.shape

torch.Size([])

In [21]:
w=torch.tensor(3.,requires_grad=True)

In [17]:
x=torch.tensor(4.)

In [22]:
b=torch.tensor(5.,requires_grad=True)

In [23]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [24]:
y.backward()

In [26]:
#print gradients
print("dy/dx",x.grad)
print("dy/dw",w.grad)
print("dy/db",b.grad)

dy/dx None
dy/dw tensor(4.)
dy/db tensor(1.)


In [28]:
#pass shape of the tensor and value 
t5=torch.full([3,2],42)
t5

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [29]:
torch.sin(t5)

tensor([[-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [32]:
import numpy as np

x1=np.array([[1,2],[3,4]])

x1

array([[1, 2],
       [3, 4]])

In [34]:
y=torch.from_numpy(x1)

->Introduction to linear regression

->Implementing a linear regression model using pytorch tensors

->Implementing a linear regression model using gradient descent

In [35]:
#inputs(temp,rainfall,humidity)
inputs=np.array([[73,67,43],
                 [91,88,64],
                 [87,134,58],
                 [102,43,37],
                 [69,96,70]],dtype='float32')

In [36]:
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [37]:
targets=np.array([[56,70],
                  [81,101],
                  [119,133],
                  [22,37],
                  [103,119]],dtype='float32')

In [39]:
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [40]:
#converting numpy arrays to tensors
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


**Linear Regression Model from Scratch**

yield_apple = w11*temp + w12*humidity + w13*rainfall

yield_orange = w21*temp + w22*humidity + w23*rainfall

In [41]:
#initializing weights and biases
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-1.0916,  1.5954,  0.3657],
        [ 0.0270, -0.4290, -0.0082]], requires_grad=True)
tensor([-1.5762,  1.6781], requires_grad=True)


In [ ]:
Y = X * Wt + B

In [42]:
def model(x):
  return x @ w.t() + b

In [43]:
#generate predictions
preds=model(inputs)
print(preds)

tensor([[ 41.3464, -25.4483],
        [ 62.8783, -34.1438],
        [138.4375, -53.9389],
        [-30.7940, -14.3192],
        [101.8515, -38.2191]], grad_fn=<AddBackward0>)


In [44]:
#compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [45]:
diff = preds - targets
torch.sum(diff * diff) / diff.numel()

tensor(9338.1348, grad_fn=<DivBackward0>)

In [46]:
diff.numel()

10

In [47]:
def mse_loss(t1, t2):
  diff = preds - targets
  return torch.sum(diff * diff) / diff.numel()

In [48]:
loss = mse_loss(preds, targets)
print(loss)

tensor(9338.1348, grad_fn=<DivBackward0>)


In [49]:
loss.backward()

In [50]:
print(w)
print(w.grad)

tensor([[-1.0916,  1.5954,  0.3657],
        [ 0.0270, -0.4290, -0.0082]], requires_grad=True)
tensor([[ -1298.3900,   -470.4536,   -539.2576],
        [-10322.4355, -12127.4541,  -7300.0171]])


In [51]:
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5

In [52]:
w, b

(tensor([[-1.0787,  1.6001,  0.3711],
         [ 0.1302, -0.3078,  0.0648]], requires_grad=True),
 tensor([-1.5760,  1.6793], requires_grad=True))

In [53]:
loss = mse_loss(model(inputs), targets)
print(loss)

tensor(9338.1348, grad_fn=<DivBackward0>)


In [55]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [57]:
#train for 100 epochs
for i in range(1,100):
  preds=model(inputs)
  loss=mse_loss(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [58]:
preds=model(inputs)
loss=mse_loss(preds,targets)
print(loss)

tensor(215.9802, grad_fn=<DivBackward0>)


In [59]:
preds

tensor([[ 53.0672,  75.6360],
        [ 76.5830, 101.2669],
        [138.0667, 123.0429],
        [ -1.4936,  66.0376],
        [105.0003, 103.5714]], grad_fn=<AddBackward0>)

In [60]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

**Linear Regression with pytorch built-ins**

In [61]:
import torch.nn as nn

In [62]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

In [63]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

In [64]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [65]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [66]:
from torch.utils.data import TensorDataset

In [67]:
train_ds=TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [68]:
from torch.utils.data import DataLoader

In [69]:
batch_size=5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [70]:
for xb,yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 74.,  66.,  43.],
        [ 87., 134.,  58.],
        [ 91.,  87.,  65.]])
tensor([[ 57.,  69.],
        [ 82., 100.],
        [ 57.,  69.],
        [119., 133.],
        [ 80., 102.]])


In [71]:
model=nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0803, -0.1546, -0.4788],
        [-0.3686, -0.2036,  0.3928]], requires_grad=True)
Parameter containing:
tensor([ 0.4410, -0.3332], requires_grad=True)


In [72]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0803, -0.1546, -0.4788],
         [-0.3686, -0.2036,  0.3928]], requires_grad=True),
 Parameter containing:
 tensor([ 0.4410, -0.3332], requires_grad=True)]

In [73]:
preds=model(inputs)
print(preds)

tensor([[-24.6414, -23.9976],
        [-36.4969, -26.6607],
        [-41.0567, -36.9104],
        [-15.7290, -32.1579],
        [-42.3736, -17.8227],
        [-24.4065, -24.1626],
        [-36.8211, -26.0642],
        [-41.4551, -36.8862],
        [-15.9639, -31.9929],
        [-42.9327, -17.0613],
        [-24.9657, -23.4011],
        [-36.2620, -26.8257],
        [-40.7324, -37.5068],
        [-15.1698, -32.9193],
        [-42.6085, -17.6577]], grad_fn=<AddmmBackward>)


In [74]:
import torch.nn.functional as F

In [75]:
loss_fn=F.mse_loss

In [76]:
loss=loss_fn(model(inputs), targets)
print(loss)

tensor(14581.7686, grad_fn=<MseLossBackward>)


In [77]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [78]:
def fit(num_epochs,model,loss_fn,opt,train_dl):
  for epoch in range(num_epochs):
    for xb,yb in train_dl:
      pred=model(xb)
      loss=loss_fn(pred,yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if((epoch+1)%10 == 0):
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1,num_epochs,loss.item()))

In [79]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100], Loss: 594.4860
Epoch [20/100], Loss: 261.1644
Epoch [30/100], Loss: 195.4435
Epoch [40/100], Loss: 177.3789
Epoch [50/100], Loss: 138.8846
Epoch [60/100], Loss: 73.3971
Epoch [70/100], Loss: 51.9347
Epoch [80/100], Loss: 38.1995
Epoch [90/100], Loss: 37.9783
Epoch [100/100], Loss: 45.8821
